"""initial

Revision ID: a60d8067d00b
Revises: 
Create Date: 2024-05-12 20:50:42.738065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a60d8067d00b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ru_tg_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tokens', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ru_tg_data'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ru_tg_data')
    # ### end Alembic commands ###
